# -*- coding: utf-8 -*-
"""Untitled0.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1PD5VLXRxIWoHnopk8pSQiK1y93GuKTP0
"""

print("Hello World")

